# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/kernel/motorola/sdm710-modules/motorola/cirrus/audio/dlkm/include

obj-m += madera-ldo1.o madera-micsupp.o
