# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel/motorola/sdm710-modules/motorola/include

obj-m += watchdogtest.o
KBUILD_EXTRA_SYMBOLS += $(KBUILD_OUTPUT)/Module.symvers
