# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel/motorola/sdm710-modules/motorola/drivers/power/mmi_charger
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel/motorola/sdm710-modules/motorola/include

obj-m += mmi_charger.o
