# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/kernel/motorola/sdm710-modules/motorola/cirrus/audio/dlkm/include
EXTRA_CFLAGS += -DCONFIG_EXTCON_MADERA_INPUT_EVENT

obj-m += extcon-madera.o
