# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel/motorola/sdm710-modules/motorola/include \
		-I$(ANDROID_BUILD_TOP)/kernel/motorola/sdm710-modules/motorola/drivers/power/mmi_sc8549

obj-m += mmi_sc8549.o


