# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/kernel/motorola/sdm710-modules/motorola/include
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/../../kernel/motorola/sdm710/Module.symvers

obj-m += qpnp-power-on-mmi.o

